# Generated by Django 4.1.5 on 2023-03-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Coffee Table', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Posted_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Table', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('subimage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True, unique=True)),
                ('size_spec', models.TextField(null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('quantity', models.IntegerField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('count_in_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('proimage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.image')),
                ('subcategory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subcategory')),
            ],
        ),
    ]
