# Generated by Django 4.1.5 on 2023-03-29 16:50

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=base.models.Product),
        ),
    ]
