# Generated by Django 4.1.5 on 2023-03-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
