# Generated by Django 4.1.5 on 2023-03-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_product_review_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
    ]
