# Generated by Django 4.1.5 on 2023-04-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_shippingaddress_order_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
